
export default {
    SET_USER: "SET_USER",
    REMOVE_USER: "REMOVE_USER",
    FETCH_USER: "FETCH_USER",
    FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
    ADD_NEW_FOOD: "ADD_NEW_FOOD",
    REMOVE_FOODS: "REMOVE_FOODS",
    REMOVE_A_FOOD: "REMOVE_A_FOOD"
}
